server:
  port: 8086
servlet:
    context-path: /api/v1/wastemanageraddressapi
spring:
  application:
    name: wastemanageraddressapi

  datasource:
    url: jdbc:h2:file:C:/Users/Cristian/test1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update  

eureka:
  client:
        register-with-eureka: true
        fetch-registry: true
  serviceUrl:
      defaultZone: http://wastemanager:adm*2024*@127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost




