server:
  port: 8081
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://wastemanager:adm*2024*@127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
  
spring:
  application:
    name: waste-manager-gateway
  cloud:
    gateway:
      routes:   
      - id: wastemanagerapi
        uri: lb://WASTEMANAGERAPI
        predicates:
        - Path=/api/v1/wastemanagerapi/**  
      - id: wastemanageraddressapi 
        uri: lb://WASTEMANAGERADDRESSAPI 
        predicates:
         - Path=/api/v1/wastemanageraddressapi/**    
        
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

